#SAMPLE PPR NODES AND EDGES 
sample_ppr_nodes={'Axle': {'attributes': [{'attr_name': 'color',
                          'data_type': 'xs:string',
                          'value': 'Green'},
                         {'attr_name': 'size',
                          'data_type': 'xs:string',
                          'value': 'Small'}],
          'class': 'Product',
          'id': '920a242f-7492-4a4b-be14-3f32aa145d50',
          'name': 'Axle',
          'parent': None,
          'port_id': 'd55e2fca-a6ae-45c9-93fa-80a6c6a67c64'},
 'Chasis': {'attributes': [{'attr_name': 'color',
                            'data_type': 'xs:string',
                            'value': 'Blue'},
                           {'attr_name': 'size',
                            'data_type': 'xs:string',
                            'value': 'Medium'}],
            'class': 'Product',
            'id': '885c5ea7-2316-4a56-a4bc-014ba388f453',
            'name': 'Chasis',
            'parent': None,
            'port_id': 'dce740d9-4126-4ce4-ba5f-c58ace748ea6'},
 'Colorant Feed': {'attributes': [],
                   'class': 'Resource',
                   'id': '2a0d6a48-bc46-407a-af9a-8641e0cd763b',
                   'name': 'Colorant Feed',
                   'parent': 'Injection Moulding Machine',
                   'port_id': '390cf5eb-ca09-40e1-b4b7-24bb5082062f'},
 'Delivery Van': {'attributes': [{'attr_name': 'color',
                                  'data_type': 'xs:string',
                                  'value': None},
                                 {'attr_name': 'size',
                                  'data_type': 'xs:string',
                                  'value': None}],
                  'class': 'Product',
                  'id': 'eedace48-136c-420c-9f1f-d51a77f65d25',
                  'name': 'Delivery Van',
                  'parent': None,
                  'port_id': '155edc84-6845-4a1e-8ca0-2a787e5f79c5'},
 'Delivery Van without Load': {'attributes': [{'attr_name': 'color',
                                               'data_type': 'xs:string',
                                               'value': None},
                                              {'attr_name': 'size',
                                               'data_type': 'xs:string',
                                               'value': None}],
                               'class': 'Product',
                               'id': '2564a93f-0de9-4bb0-810a-7e2c2439f88f',
                               'name': 'Delivery Van without Load',
                               'parent': None,
                               'port_id': '735c37d4-94b9-43f5-9523-e4c2c5ac7f2f'},
 'Drive Unit': {'attributes': [{'attr_name': 'color',
                                'data_type': 'xs:string',
                                'value': None},
                               {'attr_name': 'size',
                                'data_type': 'xs:string',
                                'value': None}],
                'class': 'Product',
                'id': 'f7100729-f717-49fd-8411-fed015b55281',
                'name': 'Drive Unit',
                'parent': None,
                'port_id': 'b1dc78ce-2139-40c4-aaa9-03149ee74971'},
 'Injection Moulding': {'attributes': [],
                        'class': 'Process',
                        'id': '8652df3b-d139-4cfd-ac3a-b89f4e0a90c7',
                        'name': 'Injection Moulding',
                        'parent': None,
                        'port_id': '55627962-3c26-4993-9bad-215eb1a14d9d'},
 'Injection Moulding Machine': {'attributes': [],
                                'class': 'Resource',
                                'id': 'd6d1a6ee-97cc-45bb-a878-5507da87ac7f',
                                'name': 'Injection Moulding Machine',
                                'parent': None,
                                'port_id': '0fba43cb-e541-4fb6-b607-0107ea136282'},
 'Load': {'attributes': [{'attr_name': 'color',
                          'data_type': 'xs:string',
                          'value': 'Black'},
                         {'attr_name': 'size',
                          'data_type': 'xs:string',
                          'value': 'Medium'}],
          'class': 'Product',
          'id': '2ffee0a9-811a-4922-9db8-8a2caaca5abe',
          'name': 'Load',
          'parent': None,
          'port_id': 'f77066ba-7d1d-4a41-a27a-907ab6a914e1'},
 'Manual Operator': {'attributes': [],
                     'class': 'Resource',
                     'id': '04105352-ebc3-4959-b4b6-c498e65b41db',
                     'name': 'Manual Operator',
                     'parent': None,
                     'port_id': '9de306f3-aeeb-4b85-bfb0-5f212bca8302'},
 'Mating': {'attributes': [],
            'class': 'Process',
            'id': '8eb92553-d42e-455a-aae3-c8cd1288e054',
            'name': 'Mating',
            'parent': None,
            'port_id': 'b7b72fdf-3937-4d46-85ec-3fd429beaae3'},
 'Mating Robot': {'attributes': [],
                  'class': 'Resource',
                  'id': '645ba529-a709-40a6-b661-9995142df3d1',
                  'name': 'Mating Robot',
                  'parent': None,
                  'port_id': '82b07f74-8239-4042-9989-2cab36ea720c'},
 'Moulding Tool': {'attributes': [],
                   'class': 'Resource',
                   'id': '2d0ae28a-ceb1-4462-95f9-854c8d055b5a',
                   'name': 'Moulding Tool',
                   'parent': 'Injection Moulding Machine',
                   'port_id': '56d9467e-bb99-4500-bf95-a3bb5aaa4cba'},
 'Phase I Interlocking': {'attributes': [],
                          'class': 'Process',
                          'id': 'a101ee82-2071-43dc-a858-2d11aec2fffe',
                          'name': 'Phase I Interlocking',
                          'parent': None,
                          'port_id': '943ccd65-015f-4ea1-9308-6517b4134d87'},
 'Phase II Interlocking': {'attributes': [],
                           'class': 'Process',
                           'id': '6be8bf51-275c-4142-af8e-4ea8a189443b',
                           'name': 'Phase II Interlocking',
                           'parent': None,
                           'port_id': 'ae012e8a-8190-4811-8432-4f1f1650c38d'},
 'Phase III Interlocking': {'attributes': [],
                            'class': 'Process',
                            'id': 'd56fffb0-588c-468b-b2ac-ca3b874a3941',
                            'name': 'Phase III Interlocking',
                            'parent': None,
                            'port_id': '0d9af5e6-b716-4493-8472-67b3fe1ac3cd'},
 'Plastic': {'attributes': [{'attr_name': 'color',
                             'data_type': 'xs:string',
                             'value': 'White'},
                            {'attr_name': 'size',
                             'data_type': 'xs:string',
                             'value': 'N/A'}],
             'class': 'Product',
             'id': '6e141c9b-21ee-4f7d-a67a-b65cd5bfd775',
             'name': 'Plastic',
             'parent': None,
             'port_id': '4b1e8e8f-074b-4072-b1db-4b3d11b7e543'},
 'Rim': {'attributes': [{'attr_name': 'color',
                         'data_type': 'xs:string',
                         'value': 'Yellow'},
                        {'attr_name': 'size',
                         'data_type': 'xs:string',
                         'value': 'Small'}],
         'class': 'Product',
         'id': '32e93b38-b990-47ec-9e29-e1ab7aec3e68',
         'name': 'Rim',
         'parent': None,
         'port_id': '72725519-2d7a-466f-9e39-18764f2c0cc9'},
 'Tyre': {'attributes': [{'attr_name': 'color',
                          'data_type': 'xs:string',
                          'value': 'Black'},
                         {'attr_name': 'size',
                          'data_type': 'xs:string',
                          'value': 'Small'}],
          'class': 'Product',
          'id': '3efd1b12-526c-4215-8672-bcc036dae65c',
          'name': 'Tyre',
          'parent': None,
          'port_id': 'c1cbf991-5cfd-4c0f-9e07-7c0c6e56a2a9'},
 'Upper Car Body': {'attributes': [{'attr_name': 'color',
                                    'data_type': 'xs:string',
                                    'value': None},
                                   {'attr_name': 'size',
                                    'data_type': 'xs:string',
                                    'value': None}],
                    'class': 'Product',
                    'id': 'eaae0c92-6905-4c36-af1b-5e270da42fa9',
                    'name': 'Upper Car Body',
                    'parent': None,
                    'port_id': '24d82185-8f64-48e3-a1ed-605c8988b88c'},
 'Wheel': {'attributes': [{'attr_name': 'color',
                           'data_type': 'xs:string',
                           'value': None},
                          {'attr_name': 'size',
                           'data_type': 'xs:string',
                           'value': None}],
           'class': 'Product',
           'id': 'cd8f9ee7-7d98-4a1d-80ee-8fc5b81c4af5',
           'name': 'Wheel',
           'parent': None,
           'port_id': '3b3992e9-812b-416c-83bd-69a07a05871d'},
 'Wheel Mounting': {'attributes': [],
                    'class': 'Process',
                    'id': 'dc655132-d519-4a3c-8688-5e4b1489d4d4',
                    'name': 'Wheel Mounting',
                    'parent': None,
                    'port_id': 'b7f3eae7-b150-4e4b-9e7c-6af3caa68f1a'},
 'Windshield': {'attributes': [{'attr_name': 'color',
                                'data_type': 'xs:string',
                                'value': 'White'},
                               {'attr_name': 'size',
                                'data_type': 'xs:string',
                                'value': 'Small'}],
                'class': 'Product',
                'id': '3d281bff-64fa-4ab3-9c4d-a642594aff7d',
                'name': 'Windshield',
                'parent': None,
                'port_id': '25146d25-597b-4de2-bdd9-8e35a2ac2191'}}

sample_ppr_edges=[{'cardinality': None,
  'name': 'Plastic_to_Injection Moulding',
  'source': 'Plastic',
  'target': 'Injection Moulding',
  'type': 'PPR_port'},
 {'cardinality': '2',
  'name': 'Load_to_Phase III Interlocking',
  'source': 'Load',
  'target': 'Phase III Interlocking',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Chasis_to_Phase I Interlocking',
  'source': 'Chasis',
  'target': 'Phase I Interlocking',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Windshield_to_Phase I Interlocking',
  'source': 'Windshield',
  'target': 'Phase I Interlocking',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Tyre_to_Mating',
  'source': 'Tyre',
  'target': 'Mating',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Rim_to_Mating',
  'source': 'Rim',
  'target': 'Mating',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Axle_to_Wheel Mounting',
  'source': 'Axle',
  'target': 'Wheel Mounting',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Upper Car Body_to_Phase II Interlocking',
  'source': 'Upper Car Body',
  'target': 'Phase II Interlocking',
  'type': 'PPR_port'},
 {'cardinality': '2',
  'name': 'Wheel_to_Wheel Mounting',
  'source': 'Wheel',
  'target': 'Wheel Mounting',
  'type': 'PPR_port'},
 {'cardinality': '2',
  'name': 'Drive Unit_to_Phase II Interlocking',
  'source': 'Drive Unit',
  'target': 'Phase II Interlocking',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Delivery Van without Load_to_Phase III Interlocking',
  'source': 'Delivery Van without Load',
  'target': 'Phase III Interlocking',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Injection Moulding Machine',
  'source': 'Injection Moulding',
  'target': 'Injection Moulding Machine',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Load',
  'source': 'Injection Moulding',
  'target': 'Load',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Chasis',
  'source': 'Injection Moulding',
  'target': 'Chasis',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Windshield',
  'source': 'Injection Moulding',
  'target': 'Windshield',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Tyre',
  'source': 'Injection Moulding',
  'target': 'Tyre',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Rim',
  'source': 'Injection Moulding',
  'target': 'Rim',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding_to_Axle',
  'source': 'Injection Moulding',
  'target': 'Axle',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Mating_to_Wheel',
  'source': 'Mating',
  'target': 'Wheel',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Mating_to_Mating Robot',
  'source': 'Mating',
  'target': 'Mating Robot',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Wheel Mounting_to_Mating Robot',
  'source': 'Wheel Mounting',
  'target': 'Mating Robot',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Wheel Mounting_to_Drive Unit',
  'source': 'Wheel Mounting',
  'target': 'Drive Unit',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Phase I Interlocking_to_Upper Car Body',
  'source': 'Phase I Interlocking',
  'target': 'Upper Car Body',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Phase I Interlocking_to_Manual Operator',
  'source': 'Phase I Interlocking',
  'target': 'Manual Operator',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Phase II Interlocking_to_Manual Operator',
  'source': 'Phase II Interlocking',
  'target': 'Manual Operator',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Phase II Interlocking_to_Delivery Van without Load',
  'source': 'Phase II Interlocking',
  'target': 'Delivery Van without Load',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Phase III Interlocking_to_Manual Operator',
  'source': 'Phase III Interlocking',
  'target': 'Manual Operator',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Phase III Interlocking_to_Delivery Van',
  'source': 'Phase III Interlocking',
  'target': 'Delivery Van',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding Machine_to_Moulding Tool',
  'source': 'Injection Moulding Machine',
  'target': 'Moulding Tool',
  'type': 'PPR_port'},
 {'cardinality': None,
  'name': 'Injection Moulding Machine_to_Colorant Feed',
  'source': 'Injection Moulding Machine',
  'target': 'Colorant Feed',
  'type': 'PPR_port'}]

#SAMPLE ENGINEERING NODES AND EDGES
sample_eng_nodes={'Axle': {'attributes': [{'attr_name': 'product_cost', 'value': '20.0 Euro'}],
          'class': 'Product',
          'name': 'Axle',
          'parent': None},
 'Chasis': {'attributes': [{'attr_name': 'product_cost', 'value': '20.0 Euro'}],
            'class': 'Product',
            'name': 'Chasis',
            'parent': None},
 'Delivery Van': {'attributes': [{'attr_name': 'product_cost',
                                  'value': '120.0 Euro'}],
                  'class': 'Product',
                  'name': 'Delivery Van',
                  'parent': None},
 'Delivery Van without Load': {'attributes': [{'attr_name': 'product_cost',
                                               'value': '100.0 Euro'}],
                               'class': 'Product',
                               'name': 'Delivery Van without Load',
                               'parent': None},
 'Drive Unit': {'attributes': [{'attr_name': 'product_cost',
                                'value': '60.0 Euro'}],
                'class': 'Product',
                'name': 'Drive Unit',
                'parent': None},
 'Injection Moulding Machine': {'attributes': [{'attr_name': 'operating_speed',
                                                'value': '20.0 Units/min'},
                                               {'attr_name': 'operating_cost',
                                                'value': '50.0 Euro'}],
                                'class': 'Resource',
                                'name': 'Injection Moulding Machine',
                                'parent': None},
 'Load': {'attributes': [{'attr_name': 'product_cost', 'value': '20.0 Euro'}],
          'class': 'Product',
          'name': 'Load',
          'parent': None},
 'Manual Operator': {'attributes': [{'attr_name': 'operating_speed',
                                     'value': '20.0 Units/min'},
                                    {'attr_name': 'operating_cost',
                                     'value': '25.0 Euro'}],
                     'class': 'Resource',
                     'name': 'Manual Operator',
                     'parent': None},
 'Mating': {'attributes': [{'attr_name': 'cycle_time',
                            'value': '17.0 seconds'}],
            'class': 'Process',
            'name': 'Mating',
            'parent': None},
 'Mating Robot': {'attributes': [{'attr_name': 'operating_speed',
                                  'value': '22.0 Units/min'},
                                 {'attr_name': 'operating_cost',
                                  'value': '27.0 Euro'}],
                  'class': 'Resource',
                  'name': 'Mating Robot',
                  'parent': None},
 'Phase I Interlocking': {'attributes': [{'attr_name': 'cycle_time',
                                          'value': '35.0 seconds'}],
                          'class': 'Process',
                          'name': 'Phase I Interlocking',
                          'parent': None},
 'Phase II Interlocking': {'attributes': [{'attr_name': 'cycle_time',
                                           'value': '36.0 seconds'}],
                           'class': 'Process',
                           'name': 'Phase II Interlocking',
                           'parent': None},
 'Phase III Interlocking': {'attributes': [{'attr_name': 'cycle_time',
                                            'value': '37.0 seconds'}],
                            'class': 'Process',
                            'name': 'Phase III Interlocking',
                            'parent': None},
 'Rim': {'attributes': [{'attr_name': 'product_cost', 'value': '20.0 Euro'}],
         'class': 'Product',
         'name': 'Rim',
         'parent': None},
 'Tyre': {'attributes': [{'attr_name': 'product_cost', 'value': '20.0 Euro'}],
          'class': 'Product',
          'name': 'Tyre',
          'parent': None},
 'Upper Car Body': {'attributes': [{'attr_name': 'product_cost',
                                    'value': '40.0 Euro'}],
                    'class': 'Product',
                    'name': 'Upper Car Body',
                    'parent': None},
 'Wheel': {'attributes': [{'attr_name': 'product_cost', 'value': '40.0 Euro'}],
           'class': 'Product',
           'name': 'Wheel',
           'parent': None},
 'Wheel Mounting': {'attributes': [{'attr_name': 'cycle_time',
                                    'value': '20.0 seconds'}],
                    'class': 'Process',
                    'name': 'Wheel Mounting',
                    'parent': None},
 'Windshield': {'attributes': [{'attr_name': 'product_cost',
                                'value': '20.0 Euro'}],
                'class': 'Product',
                'name': 'Windshield',
                'parent': None}}

sample_eng_edges=[{'name': 'Injection Moulding Machine_to_Load',
  'source': 'Injection Moulding Machine',
  'target': 'Load',
  'type': 'contributes_to'},
 {'name': 'Injection Moulding Machine_to_Chasis',
  'source': 'Injection Moulding Machine',
  'target': 'Chasis',
  'type': 'contributes_to'},
 {'name': 'Injection Moulding Machine_to_Windshield',
  'source': 'Injection Moulding Machine',
  'target': 'Windshield',
  'type': 'contributes_to'},
 {'name': 'Injection Moulding Machine_to_Tyre',
  'source': 'Injection Moulding Machine',
  'target': 'Tyre',
  'type': 'contributes_to'},
 {'name': 'Injection Moulding Machine_to_Rim',
  'source': 'Injection Moulding Machine',
  'target': 'Rim',
  'type': 'contributes_to'},
 {'name': 'Injection Moulding Machine_to_Axle',
  'source': 'Injection Moulding Machine',
  'target': 'Axle',
  'type': 'contributes_to'},
 {'name': 'Chasis_to_Upper Car Body',
  'source': 'Chasis',
  'target': 'Upper Car Body',
  'type': 'part_of'},
 {'name': 'Windshield_to_Upper Car Body',
  'source': 'Windshield',
  'target': 'Upper Car Body',
  'type': 'part_of'},
 {'name': 'Tyre_to_Wheel',
  'source': 'Tyre',
  'target': 'Wheel',
  'type': 'part_of'},
 {'name': 'Rim_to_Wheel',
  'source': 'Rim',
  'target': 'Wheel',
  'type': 'part_of'},
 {'name': 'Upper Car Body_to_Delivery Van without Load',
  'source': 'Upper Car Body',
  'target': 'Delivery Van without Load',
  'type': 'part_of'},
 {'name': 'Drive Unit_to_Delivery Van without Load',
  'source': 'Drive Unit',
  'target': 'Delivery Van without Load',
  'type': 'part_of'},
 {'name': 'Wheel_to_Drive Unit',
  'source': 'Wheel',
  'target': 'Drive Unit',
  'type': 'part_of'},
 {'name': 'Axle_to_Drive Unit',
  'source': 'Axle',
  'target': 'Drive Unit',
  'type': 'part_of'},
 {'name': 'Load_to_Delivery Van',
  'source': 'Load',
  'target': 'Delivery Van',
  'type': 'part_of'},
 {'name': 'Delivery Van without Load_to_Delivery Van',
  'source': 'Delivery Van without Load',
  'target': 'Delivery Van',
  'type': 'part_of'},
 {'name': 'Manual Operator_to_Upper Car Body',
  'source': 'Manual Operator',
  'target': 'Upper Car Body',
  'type': 'contributes_to'},
 {'name': 'Manual Operator_to_Delivery Van',
  'source': 'Manual Operator',
  'target': 'Delivery Van',
  'type': 'contributes_to'},
 {'name': 'Manual Operator_to_Delivery Van without Load',
  'source': 'Manual Operator',
  'target': 'Delivery Van without Load',
  'type': 'contributes_to'},
 {'name': 'Mating Robot_to_Wheel',
  'source': 'Mating Robot',
  'target': 'Wheel',
  'type': 'contributes_to'},
 {'name': 'Mating Robot_to_Drive Unit',
  'source': 'Mating Robot',
  'target': 'Drive Unit',
  'type': 'contributes_to'},
 {'name': 'Manual Operator_to_Phase I Interlocking',
  'source': 'Manual Operator',
  'target': 'Phase I Interlocking',
  'type': 'impacts'},
 {'name': 'Manual Operator_to_Phase II Interlocking',
  'source': 'Manual Operator',
  'target': 'Phase II Interlocking',
  'type': 'impacts'},
 {'name': 'Manual Operator_to_Phase III Interlocking',
  'source': 'Manual Operator',
  'target': 'Phase III Interlocking',
  'type': 'impacts'},
 {'name': 'Phase I Interlocking_to_Phase II Interlocking',
  'source': 'Phase I Interlocking',
  'target': 'Phase II Interlocking',
  'type': 'constraints'},
 {'name': 'Phase II Interlocking_to_Phase III Interlocking',
  'source': 'Phase II Interlocking',
  'target': 'Phase III Interlocking',
  'type': 'constraints'},
 {'name': 'Mating_to_Wheel Mounting',
  'source': 'Mating',
  'target': 'Wheel Mounting',
  'type': 'constraints'},
 {'name': 'Mating Robot_to_Mating',
  'source': 'Mating Robot',
  'target': 'Mating',
  'type': 'impacts'},
 {'name': 'Mating Robot_to_Wheel Mounting',
  'source': 'Mating Robot',
  'target': 'Wheel Mounting',
  'type': 'impacts'}]

#SAMPLE SUSTAINABLITY NODES AND EDGES
sample_sus_nodes={'Axle': {'attributes': [{'attr_name': 'durability', 'value': '2.0 years'},
                         {'attr_name': 'co2_per_unit', 'value': '1.0 kg/unit'}],
          'class': 'Product',
          'name': 'Axle',
          'parent': None},
 'Chasis': {'attributes': [{'attr_name': 'durability', 'value': '2.0 years'},
                           {'attr_name': 'co2_per_unit',
                            'value': '1.0 kg/unit'}],
            'class': 'Product',
            'name': 'Chasis',
            'parent': None},
 'Colorant Feed': {'attributes': [{'attr_name': 'energy_flow_rate',
                                   'value': '0.0 KW/hr'}],
                   'class': 'Resource',
                   'name': 'Colorant Feed',
                   'parent': 'Injection Moulding Machine'},
 'Delivery Van': {'attributes': [{'attr_name': 'durability',
                                  'value': '2.0 years'},
                                 {'attr_name': 'co2_per_unit',
                                  'value': '0.0 kg/unit'}],
                  'class': 'Product',
                  'name': 'Delivery Van',
                  'parent': None},
 'Delivery Van without Load': {'attributes': [{'attr_name': 'durability',
                                               'value': '2.0 years'},
                                              {'attr_name': 'co2_per_unit',
                                               'value': '15.0 kg/unit'}],
                               'class': 'Product',
                               'name': 'Delivery Van without Load',
                               'parent': None},
 'Drive Unit': {'attributes': [{'attr_name': 'durability',
                                'value': '2.0 years'},
                               {'attr_name': 'co2_per_unit',
                                'value': '4.0 kg/unit'}],
                'class': 'Product',
                'name': 'Drive Unit',
                'parent': None},
 'Injection Moulding': {'attributes': [{'attr_name': 'specific_energy_consumption',
                                        'value': '30.0 KW/unit'},
                                       {'attr_name': 'co2_emission',
                                        'value': '60.0 kg/hr'}],
                        'class': 'Process',
                        'name': 'Injection Moulding',
                        'parent': None},
 'Load': {'attributes': [{'attr_name': 'durability', 'value': '2.0 years'},
                         {'attr_name': 'co2_per_unit', 'value': '1.0 kg/unit'}],
          'class': 'Product',
          'name': 'Load',
          'parent': None},
 'Manual Operator': {'attributes': [{'attr_name': 'energy_flow_rate',
                                     'value': '20.0 KW/hr'}],
                     'class': 'Resource',
                     'name': 'Manual Operator',
                     'parent': None},
 'Mating': {'attributes': [{'attr_name': 'specific_energy_consumption',
                            'value': '13.0 KW/unit'},
                           {'attr_name': 'co2_emission',
                            'value': '17.0 kg/hr'}],
            'class': 'Process',
            'name': 'Mating',
            'parent': None},
 'Mating Robot': {'attributes': [{'attr_name': 'energy_flow_rate',
                                  'value': '30.0 KW/hr'}],
                  'class': 'Resource',
                  'name': 'Mating Robot',
                  'parent': None},
 'Moulding Tool': {'attributes': [{'attr_name': 'energy_flow_rate',
                                   'value': '50.0 KW/hr'}],
                   'class': 'Resource',
                   'name': 'Moulding Tool',
                   'parent': 'Injection Moulding Machine'},
 'Phase I Interlocking': {'attributes': [{'attr_name': 'specific_energy_consumption',
                                          'value': '15.0 KW/unit'},
                                         {'attr_name': 'co2_emission',
                                          'value': '25.0 kg/hr'}],
                          'class': 'Process',
                          'name': 'Phase I Interlocking',
                          'parent': None},
 'Phase II Interlocking': {'attributes': [{'attr_name': 'specific_energy_consumption',
                                           'value': '15.0 KW/unit'},
                                          {'attr_name': 'co2_emission',
                                           'value': '25.0 kg/hr'}],
                           'class': 'Process',
                           'name': 'Phase II Interlocking',
                           'parent': None},
 'Phase III Interlocking': {'attributes': [{'attr_name': 'specific_energy_consumption',
                                            'value': '15.0 KW/unit'},
                                           {'attr_name': 'co2_emission',
                                            'value': '25.0 kg/hr'}],
                            'class': 'Process',
                            'name': 'Phase III Interlocking',
                            'parent': None},
 'Rim': {'attributes': [{'attr_name': 'durability', 'value': '2.0 years'},
                        {'attr_name': 'co2_per_unit', 'value': '1.0 kg/unit'}],
         'class': 'Product',
         'name': 'Rim',
         'parent': None},
 'Tyre': {'attributes': [{'attr_name': 'durability', 'value': '2.0 years'},
                         {'attr_name': 'co2_per_unit', 'value': '1.0 kg/unit'}],
          'class': 'Product',
          'name': 'Tyre',
          'parent': None},
 'Upper Car Body': {'attributes': [{'attr_name': 'durability',
                                    'value': '2.0 years'},
                                   {'attr_name': 'co2_per_unit',
                                    'value': '3.0 kg/unit'}],
                    'class': 'Product',
                    'name': 'Upper Car Body',
                    'parent': None},
 'Wheel': {'attributes': [{'attr_name': 'durability', 'value': '2.0 years'},
                          {'attr_name': 'co2_per_unit',
                           'value': '2.0 kg/unit'}],
           'class': 'Product',
           'name': 'Wheel',
           'parent': None},
 'Wheel Mounting': {'attributes': [{'attr_name': 'specific_energy_consumption',
                                    'value': '13.0 KW/unit'},
                                   {'attr_name': 'co2_emission',
                                    'value': '17.0 kg/hr'}],
                    'class': 'Process',
                    'name': 'Wheel Mounting',
                    'parent': None}}
sample_sus_edges=[{'name': 'Manual Operator_to_Phase I Interlocking',
  'source': 'Manual Operator',
  'target': 'Phase I Interlocking',
  'type': 'energy_flows'},
 {'name': 'Manual Operator_to_Phase II Interlocking',
  'source': 'Manual Operator',
  'target': 'Phase II Interlocking',
  'type': 'energy_flows'},
 {'name': 'Manual Operator_to_Phase III Interlocking',
  'source': 'Manual Operator',
  'target': 'Phase III Interlocking',
  'type': 'energy_flows'},
 {'name': 'Mating Robot_to_Mating',
  'source': 'Mating Robot',
  'target': 'Mating',
  'type': 'energy_flows'},
 {'name': 'Mating Robot_to_Wheel Mounting',
  'source': 'Mating Robot',
  'target': 'Wheel Mounting',
  'type': 'energy_flows'},
 {'name': 'Moulding Tool_to_Injection Moulding',
  'source': 'Moulding Tool',
  'target': 'Injection Moulding',
  'type': 'energy_flows'},
 {'name': 'Colorant Feed_to_Injection Moulding',
  'source': 'Colorant Feed',
  'target': 'Injection Moulding',
  'type': 'material_flows'},
 {'name': 'Phase I Interlocking_to_Upper Car Body',
  'source': 'Phase I Interlocking',
  'target': 'Upper Car Body',
  'type': 'influences'},
 {'name': 'Phase II Interlocking_to_Delivery Van without Load',
  'source': 'Phase II Interlocking',
  'target': 'Delivery Van without Load',
  'type': 'influences'},
 {'name': 'Phase III Interlocking_to_Delivery Van',
  'source': 'Phase III Interlocking',
  'target': 'Delivery Van',
  'type': 'influences'},
 {'name': 'Mating_to_Wheel',
  'source': 'Mating',
  'target': 'Wheel',
  'type': 'influences'},
 {'name': 'Wheel Mounting_to_Drive Unit',
  'source': 'Wheel Mounting',
  'target': 'Drive Unit',
  'type': 'influences'},
 {'name': 'Injection Moulding_to_Load',
  'source': 'Injection Moulding',
  'target': 'Load',
  'type': 'influences'},
 {'name': 'Injection Moulding_to_Chasis',
  'source': 'Injection Moulding',
  'target': 'Chasis',
  'type': 'influences'},
 {'name': 'Injection Moulding_to_Tyre',
  'source': 'Injection Moulding',
  'target': 'Tyre',
  'type': 'influences'},
 {'name': 'Injection Moulding_to_Rim',
  'source': 'Injection Moulding',
  'target': 'Rim',
  'type': 'influences'},
 {'name': 'Injection Moulding_to_Axle',
  'source': 'Injection Moulding',
  'target': 'Axle',
  'type': 'influences'}]